transcom/move.mil

Makefile
adding more make commands 
run `make cr` on an installed site, the cache should be rebuilt
=> just adding some more commonly used commands to the make file

composer.json, composer.lock, config/sync/README.txt, config/sync/core.extension.yml
I have…
adds drop down menus for admin toolbar
```
make up
make cim
#login
#visually verify that the menus have dropdowns
```
https://www.dropbox.com/s/vycqf9zo81i8jsq/Screenshot%202018-03-27%2010.19.58.png?dl=0
=> installed and enabled admin toolbar closes #16

config/sync/block.block.mainmenu.yml, config/sync/block.block.move_mil_main_menu.yml, config/sync/core.extension.yml, config/sync/system.menu.main_menu.yml, config/sync/system.menu.moving_guide.yml, config/sync/system.menu.resources.yml, web/themes/custom/move_mil/preprocess/block/block__system_menu_block__main_menu.preprocess.inc, web/themes/custom/move_mil/preprocess/menu/menu__main_menu.preprocess.inc, web/themes/custom/move_mil/scss/_variables.scss, web/themes/custom/move_mil/scss/components/_usa-header-extended.scss, web/themes/custom/move_mil/scss/components/_usa-nav.scss, web/themes/custom/move_mil/scss/uswds.scss, web/themes/custom/move_mil/templates/layout/page.html.twig
I have…
- adjusts our styling of the custom main navigation menu to align with the themes preprocesses and render with assigned variables, styled by 18f guidelines and enhanced with specificity to align with move.mil live site.
checkout changes locally
import configuration
navigate to any home page
nav should appear on desktop
once the custom module is updated to enhance our sub navigation items sub nav should appear on desktop
to review changes now
select Structure > Menus > Main Menu > Edit > Tutorial > Edit > assign parent link to Moving Guide > save and return to site
nav should appear on mobile breakpoints
and expanded
see details …
=> Feature 33 theme global menu navigation

web/themes/custom/move_mil/.eslintrc.json, web/themes/custom/move_mil/.stylelintrc.json, web/themes/custom/move_mil/config/build.js, web/themes/custom/move_mil/config/doc-util.js, web/themes/custom/move_mil/config/flags.js, web/themes/custom/move_mil/config/fonts.js, web/themes/custom/move_mil/config/images.js, web/themes/custom/move_mil/config/javascript.js, web/themes/custom/move_mil/config/sass.js, web/themes/custom/move_mil/gulpfile.js, web/themes/custom/move_mil/move_mil.info.yml, web/themes/custom/move_mil/move_mil.libraries.yml, web/themes/custom/move_mil/package-lock.json, web/themes/custom/move_mil/package.json
I forgot to include/update the README docs for this, but for the purposes of testing this pull request, here are the important steps (I'll copy it over shortly but want to get this into the review pipeline ASAP):
1. Pull this branch
2. In your terminal, navigate to the theme folder: `cd <project root>/web/themes/custom/move_mil`
3. run `npm install`
1. In your command line, run `npm run clean` to remove any legacy files in your `assets` folder
2. check the `assets` folder. It should be empty other than a `.gitkeep` file. Manually delete any other remaining files.
3. In your command line, run `npm run lint` to try out linting css and js code. With this current code base, the css linter should error out due to exactly one breaking error, though there will be a few other warning-level …
=> custom gulp and npm setup

web/modules/custom/custom_move_mil_menus/custom_move_mil_menus.links.menu.yml
Fix for Pivotal bug https://www.pivotaltracker.com/story/show/156548068.
I have…
- Updates the links.menu.yml file within the custom module handling the main nav menu.
- Changes "Entitlements" to "Entitlements/Guidelines" to match live move.mil
- Redirects target of "Entitlements" link to "/entitlements" instead of "/moving-guide/entitlements"
- Updates three other menu items to exactly match live site: Overseas Moves (OCONUS), TDY Moves, and Retirees/Separatees. All three had been made singular while the live site is plural.
1. pull code
1. clear cache
1. text of all menu links should exactly match live site
1. clicking on the "Moving Guide => Entitlements" link should go to a live page at …
=> updated main menu links to match live site

composer.lock
composer .lock got out of date with my updates
=> missed .lock

web/themes/custom/move_mil/scss/01-atoms/_attr.scss, web/themes/custom/move_mil/scss/03-organisms/_usa-footer-secondary_section.scss, web/themes/custom/move_mil/scss/03-organisms/_usa-header-extended.scss, web/themes/custom/move_mil/scss/03-organisms/_usa-nav.scss, web/themes/custom/move_mil/templates/layout/page.html.twig
I have…
- adds some static content and styles to our footer
- includes a global style for abbr[title] to allow user agent stylesheet to address
- fixes some lint errors
1. pull branch locally
2. cd /move-mil/web/themes/custom/move_mil
3. npm run build
4. visit site to see that the footer is now rendering as follows...
**Desktop**
**Mobile**
=> Feature 156620426 update theme global footer

web/themes/custom/move_mil/js/scrollFix.js, web/themes/custom/move_mil/templates/system/paragraph/paragraph.html.twig
I have…
1. Changed scroll on clicking a jump link to be smoother and place the target part-way down the page rather than at the very top, which can be confusing to the user.
1. Changed the paragraph id format from `paragraph/{id}` to `paragraph-{id}` in order to avoid a jquery error. Note that the jumplinks module functionality will need to be updated accordingly for the links to work.
1. pull code
1. run `npm run build` from the theme root to compile js change
=> code changes for jumplinks

config/sync/editor.editor.full_html.yml, config/sync/filter.format.full_html.yml
I have…
- adds a dropdown styles selector in the WYSIWYG CK Editor
- adds custom select styles for columns to include
-  column(1/4)
-  column(1/3)
-  column(1/2)
-  column(2/3)
1. pull locally
2. make cim
3. cd /move-mil/web/themes/custom/move_mil
4. npm run build
5. make cr
6. create a basic page w/ a basic text paragraph
7. select Full HTML
8. Drop in some Lorem Ipsum
9. highlight text
10. from the "Styles" drop down in the WYSIWYG editor select one of the custom column styles
11. rinse and repeat :) you should be able to create content that appears like the image below
=> new styles dropdown for adding collumns to our WYSISYG editor

config/sync/editor.editor.full_html.yml, config/sync/filter.format.full_html.yml, web/themes/custom/move_mil/scss/02-molecules/_pro-tip.scss
I have…
- adds a dropdown styles selector in the WYSIWYG CK Editor
- adds custom select styles for columns to include
-  pro-tip full width
1. pull locally
2. make cim
3. cd /move-mil/web/themes/custom/move_mil
4. npm run build
5. make cr
6. create a basic page w/ a basic text paragraph
7. select Full HTML
8. Drop in some Lorem Ipsum
9. highlight text
10. from the "Styles" drop down in the WYSIWYG editor select pro-tips style
you should be able to create the following content
=> Feature 156725756 add pro tip class to wysiwyg styles

config/sync/editor.editor.full_html.yml, config/sync/filter.format.full_html.yml, web/themes/custom/move_mil/scss/01-atoms/_approvals.scss, web/themes/custom/move_mil/scss/02-molecules/_pro-tip.scss
I have…
- adds a dropdown styles selector in the WYSIWYG CK Editor
- adds custom select styles for columns to include
-  Tag as Unapproved
-  Tag as Approved
-  Tag as Semi-Approved
1. pull locally
2. make cim
3. cd /move-mil/web/themes/custom/move_mil
4. npm run build
5. make cr
6. create a basic page w/ a basic text paragraph
7. select Full HTML
8. Drop in some Lorem Ipsum
9. highlight text
10. from the "Styles" drop down in the WYSIWYG editor select one of the custom approval styles
11. rinse and repeat :) you should be able to create content that appears like the image below
=> Feature 156729547 add gyg class to wysiwyg styles

config/sync/block.block.jumplinks.yml
I have…
- Place jump links block in "first sidebar" region
1. Update jumplinks module with block changes
1. go to a moving guide page, and you'll see the link in the sidebar first region
=> add jumplinks block

config/sync/core.entity_form_display.paragraph.callout_accordion.default.yml, config/sync/core.entity_form_display.paragraph.customer_service_box.default.yml, config/sync/core.entity_view_display.paragraph.callout_accordion.default.yml, config/sync/core.entity_view_display.paragraph.customer_service_box.default.yml, config/sync/field.field.paragraph.callout_accordion.field_callout_content.yml, config/sync/field.field.paragraph.callout_accordion.field_callout_title.yml, config/sync/field.field.paragraph.customer_service_box.field_comm_fax.yml, config/sync/field.field.paragraph.customer_service_box.field_dsn_fax.yml, config/sync/field.field.paragraph.customer_service_box.field_other_details.yml, config/sync/field.field.paragraph.customer_service_box.field_service_description.yml, config/sync/field.storage.paragraph.field_callout_content.yml, config/sync/field.storage.paragraph.field_callout_title.yml, config/sync/field.storage.paragraph.field_comm_fax.yml, config/sync/field.storage.paragraph.field_dsn_fax.yml, config/sync/field.storage.paragraph.field_other_details.yml, config/sync/field.storage.paragraph.field_service_description.yml, config/sync/paragraphs.paragraphs_type.callout_accordion.yml
I have…
- adds new fields for customer service paragraph
- comm-fax, dsn-fax, description, other details
- new weights for fields
- new parent paragraph callout accordion
- paragraph reference
- title
1. pull branch locally
2. make cim
3. create a basic page
4. add Callout Paragraph
5. add Customer Service Paragraph type(s)
you should be able to create the following (right side representation) on the front end
=> Feature 156705960 update customer service pgraph config

web/themes/custom/move_mil/preprocess/system/breadcrumb.preprocess.inc, web/themes/custom/move_mil/scss/01-atoms/_approvals.scss, web/themes/custom/move_mil/scss/02-molecules/_breadcrumbs.scss, web/themes/custom/move_mil/scss/02-molecules/_paragraph--customer-service-box.scss, web/themes/custom/move_mil/scss/02-molecules/_pro-tip.scss, web/themes/custom/move_mil/scss/03-organisms/_move-mil--tutorial.scss, web/themes/custom/move_mil/scss/04-pages/_svc-two-col-content.scss, web/themes/custom/move_mil/templates/system/block/breadcrumb.html.twig
I have…
- cleaning up function-url-quotes, at-rule-empty-line-before, indentation, string-quotes
2. cd /web/themes/custom/move_mil
3. confirm the following do not throw warnings
- **_approvals.scss**
-  no string-quotes warnings
- **_breadcrumbs.scss**
-  no indentation warnings
- **_paragraph--customer-service-box.scss**
-  no string-quotes warnings
-  no indentation warnings
- **_pro-tip.scss**
-  no function-url-quotes warnings
- **_svc-two-col-content.scss**
-  no at-rule-empty-line-before warnings
=> Fix linting errors

web/themes/custom/move_mil/scss/04-pages/_page--front.scss
I have…
- includes updated scss $variables
compare the diffs in to our _variable partial and their assignments
=> updated some properties to use or variables

web/modules/custom/custom_move_mil_menus/custom_move_mil_menus.links.menu.yml
I have…
- Address pivotal ticket https://www.pivotaltracker.com/story/show/157090498
- Change menu items settings
1. Pull branch, execute `make menu-update`
1. Navigate to *Service Specific Information* and ensure the URL is `/service-specific-information`
1. Navigate to *Tools & Resources* and ensure the first label link is *Helpful Links* and the link is still working.
https://cl.ly/2E2B3B2c0N2n
https://cl.ly/2k2O0Q1s3g33
=> Change menu items settings

composer.lock
=> core update

web/themes/custom/move_mil/scss/02-molecules/_field--name-field-page-intro-text.scss, web/themes/custom/move_mil/scss/03-organisms/_move-mil--tutorial.scss, web/themes/custom/move_mil/templates/content/node--tutorial.html.twig
I have…
- adjusted our template, updated our styles partials to layout the UI for tutorials content more similar to the homepage
1. pull code locally
2. cd /web/themes/custom/move_mil
3. npm run build
4. navigate to a tutorial page, ie. /tutorials/new-user-registration
you should now see that our tutorials have a blue box printing above our tutorial slide carousels
=> Feature 156652533 theme tutorial intro text

web/sites/default/services.yml
I have…
- Adds configuration for CORS, so it is a bit easier and faster for decoupled apps to test against Drupal, I only added exceptions for localhost, localhost:3000 and localhost:3001
1. Pull changes
2. Clear caches
3. Try to make a request from javascript to the Drupal development server
=> Added CORS configuration for localhost

composer.json, composer.lock, config/sync/block.block.customerservice.yml, config/sync/block.block.homepagehelpfullinks.yml, config/sync/block.block.homepageheroimage.yml, config/sync/block.block.movingtips.yml, config/sync/block.block.retireeandseparateemoves.yml, config/sync/block.block.servicespecific.yml, config/sync/block.block.tutorial.yml, config/sync/core.entity_form_display.node.page.default.yml, config/sync/system.menu.customer-service.yml, config/sync/system.menu.main_menu.yml, config/sync/system.menu.moving-tips.yml, config/sync/system.menu.moving_guide.yml, config/sync/system.menu.resources.yml, config/sync/system.menu.retiree-separatee.yml, config/sync/system.menu.service-specific.yml, config/sync/system.menu.tutorial.yml, web/themes/custom/move_mil/scss/01-atoms/_back-to-top.scss, web/themes/custom/move_mil/scss/02-molecules/_breadcrumbs.scss, web/themes/custom/move_mil/templates/layout/page.html.twig
This PR builds on (and thus includes) just-created #127 for simplicity's sake. They're largely separate in substance, but I'd already made the composer changes reflected in this one before I started working on that other change (while waiting for a needed db dump Monday afternoon) and didn't want to blow them up.
This one contains the config associated with Feld's menu creation on alpha, captured through that environment database and included in a db dump.
I have…
- Adds config with menus and associated blocks for each of the special case instances of jump links.
- Updates the composer.lock file to incorporate the update to the jump links module
- Updates the composer.json to integrate the fix for the ckeditor bug. @scottqueen-bixal walked me through …
=> Custom jumplink menus config INCLUDES PR #127

composer.lock
=> hotfix for ckeditor http issue

web/modules/custom/parser/src/Controller/PpmEstimatorController.php
I have…
- Uses the correct column name in discounts table.
- Make the correct linehaul query when the weight is less than 1000 lbs.
- Explicitly cast to float the variables used in the calculation, since I was losing some cents :(. The identified problem was only with the pack and unpack charges, but I did it everywhere just in case.
1. Pull this branch.
1. Have a google maps API key.
1. Call /parser/ppm_estimate and compare results with the live site move.mil.
=> Preserve decimal numbers for all the calculations.

web/themes/custom/move_mil/scss/03-organisms/_usa-nav.scss, web/themes/custom/move_mil/scss/04-pages/_page--front.scss
IE11 triage, covering Pivotal stories [157775808 - main nav alignment](https://www.pivotaltracker.com/story/show/157775808) and [157775868 - home page service-specific images](https://www.pivotaltracker.com/story/show/157775868). 
I have…
- Removes the flex container on the main nav wrapper, center-aligns text, and left-aligns the subnav text to compensate.
- Adds a set width property to the max-width property on each service-specific icon wrapper in the home page section right above the footer.
1. Pull code
1. Compile theme assets
1. Open the home page in Win10/IE11 on Browserstack or another emulator to check the two affected sections.
Forthcoming........
=> IE11 flexbox triage

web/themes/custom/move_mil/scss/01-atoms/_facebook-link.scss, web/themes/custom/move_mil/scss/02-molecules/_paragraph--type--tabular-data-wrapper.scss
Executes [Pivotal ticket 157485059](https://www.pivotaltracker.com/story/show/157485059), fixing a bug that treated some images within the main body area of tabular data paragraphs in an unexpected way. 
Note that markup changes will be necessary on the staging site to fully complete one of the cases specified in that ticket, so please alert Feld when this update is deployed to that site.
I have…
- fixes image alignment in tabular data paragraphs, restricting the previous treatment to images on the lefthand side of each row
- adds custom treatment for facebook links with icons, as they appear on the Customer Service page
1. Pull code
1. Compile theme assets
1. Check Moving Guide and Customer Service …
=> Tabular data paragraph image fix 

web/modules/custom/parser/src/Controller/LocationsController.php
I have…
- Change the distance method, since the previous one wasn't working for long-distances.
- Javascript sorts the response in alphabetical order and Justin needs to sort it by distance again. So, I removed the sorting in the back-end side.
- There are offices duplicated, and the live site is showing those duplicates, so I changed the array to show them.
1. Call /parser/locator-maps and make sure there are 414 offices.
=> Change distance method and do not override duplicates.

web/modules/custom/parser/src/Form/FilesAndTablesManagerForm.php
I have…
Is a hotfix for the truncate messaging, because it was outside of the If-case it would add the message every time to the messaging queue.
Run a truncate and you'll see that it only shows the appropriate  truncate messages.
=> HOTFIX: Fixed error in truncate messaging

config/sync/core.entity_form_display.block_content.hero_image.default.yml, config/sync/core.entity_form_display.paragraph.tabular_data.default.yml, config/sync/core.entity_view_display.block_content.hero_image.default.yml, config/sync/core.entity_view_display.block_content.hero_image.full.yml, config/sync/core.entity_view_display.node.faq.teaser.yml, config/sync/core.entity_view_display.node.location.teaser.yml, config/sync/core.entity_view_display.paragraph.tabular_data.default.yml, config/sync/core.extension.yml, config/sync/field.field.node.faq.field_image.yml, config/sync/field.field.paragraph.tabular_data.field_tabular_image.yml, config/sync/field.field.paragraph.text_with_image.field_image.yml, config/sync/views.view.faqs.yml
I have…
- Removed svg_image dependency in the config files
- Uninstalled svg_image module
- Did not remove svg_image code yet
1. `make cim`
1. Verify FAQ is working
=> Remove svg module

lib/data/transportation_offices.json, lib/data/weight_scales.json
Implements [four](https://www.pivotaltracker.com/story/show/157976526) [simple](https://www.pivotaltracker.com/story/show/157856121) [location](https://www.pivotaltracker.com/story/show/157855922) [updates](https://www.pivotaltracker.com/story/show/157856063) requested through the DoD Github issue queue.
This change shouldn't actually affect anything upon deployment without re-running the associated data parsers. That may turn out to be necessary due to the limitations of content entry through the Drupal admin UI, which is why I wanted to get these changes merged into the code base sooner rather than later.
I have…
- Incorporates a few address changes to Location items (PPPOs and weight scales) already made on the staging site into their source data …
=> Location changes requested by those locations - already changed in staging content

Makefile, lib/data/transportation_offices.json, web/modules/custom/parser/src/Controller/LocationsController.php
Update locator controller to read from telephone paragraph instead of the previous string field.
I have…
- Since location content type change, this locator controller needed to change. The phone field is now a paragraph and the parser method needs to fetch the values differently.
- Fetch the paragraph reference, load the paragraph, and fetch the 3 phone fields: number, dsn, and type.
1. With the office locations updated. Call the locator map with: `{{host}}/parser/locator-maps`
The phones in the answer must look like this:
```
"phones": {
"1594": {
"field_phonenumber": [
{
"value": …
```
=> Read from telephone paragraph instead of single string field.

.ebextensions/packages.config
I have…
Add the building instructions for the entitlements form (part of react-tools).
=> Add entitlements page to build script

composer.json, composer.lock, config/sync/core.extension.yml
I have…
- installs admin_toolbar with composer and updates the enabled configuration for the module 
2. make cim
3. make cr
4. make uli
5. login
6. check to see that the following modules are enabled
- advaced_help
if you filter by key work "Advanced help" you will get a result that looks like this
=> Feature 157967188 install enable advanced help module

web/modules/custom/parser/js/parser.js
=> Changed message on alert when deleting tables for the parser

web/modules/custom/react_tools/tools/react-entitlements-page/package-lock.json, web/modules/custom/react_tools/tools/react-entitlements-page/src/index.js, web/modules/custom/react_tools/tools/react-locator-map/src/index.js, web/modules/custom/react_tools/tools/react-locator-map/src/sass/main.scss, web/modules/custom/react_tools/tools/react-ppm-tool/src/index.js, web/modules/custom/react_tools/tools/react-ppm-tool/src/sass/main.scss, web/modules/custom/react_tools/tools/react-weight-estimator/src/index.js
This PR resolves Pivotal stories [#158502447 - locator map pin icons too large in IE on Win7/Win8](https://www.pivotaltracker.com/story/show/158502447), [#158502581 - tools not appearing at all on IE10](https://www.pivotaltracker.com/story/show/158502581), and [#158503129 - no icon on locator map's validation popup](https://www.pivotaltracker.com/story/show/158503129).
I have…
- Sets fixed widths on the :before elements referencing svg icons representing locator map pins
- Changes the file reference in the locator map's validation popup to the correct path, so the icon appears. Aligns the placement of that icon on popups for both the locator map tool and the PPM tool.
- In each tool's index.js file, adds two imports necessary to get React working …
=> IE tools fixes

config/sync/field.field.node.location.field_location_telephone.yml, config/sync/field.field.paragraph.location_telephone.field_phonenumber.yml
This PR completes Pivotal story [#158392940 - require phone number for locations](https://www.pivotaltracker.com/story/show/158392940)
I have…
- Changes config to make the `location_telephone` field required.
- Changes config to make the `phonenumber` field within the `location_telephone` paragraph required.
1. Pull code
1. Go to create a new item of Location content type
Before:
After:
=> Require phone field on locations

config/sync/system.performance.yml
Adding cache settings to avoid having caching removed on the staging or production environments.
=> Adding cache settings

config/sync/core.entity_form_display.node.location.default.yml, config/sync/core.entity_view_display.node.location.default.yml, config/sync/field.field.node.location.field_location_cnsl_id.yml, config/sync/field.storage.node.field_location_cnsl_id.yml, web/modules/custom/parser/parser.services.yml, web/modules/custom/parser/src/Form/FilesAndTablesManagerForm.php, web/modules/custom/parser/src/Service/DbWriter.php, web/modules/custom/parser/src/Service/XMLReader.php
I have…
- Adds the ability to upload an xml file to update the locations phones, address, and e-mails.
- Parses the xml file, searchs by CNSL id, updates the locations found.
1. pull the branch
1. execute config import
1. go to http://move.mil.localhost:8000/admin/config/parser/manager
1. Scroll down to locations and expand the option.
1. upload the xml file provided by US transcom
1. verify that nodes with CNSL id, that exists on the xml file, are updated.
=> Xml parser

Dockerrun.aws.json
=> add app tag for docker building script

composer.json, composer.lock, config/sync/core.extension.yml, config/sync/google_analytics.settings.yml
I have…
- Installs Google Analytics module.
1. Pull changes
1. execute composer install
1. execute config import
=> Add google analytics module

web/modules/custom/parser/src/Form/FilesAndTablesManagerForm.php
I have…
- Adds 20 MG as the file limit size for us zip codes and locations which are large files.
1. deploy changes to staging
2. upload files, you shouldn't see an error.
=> Set 20MB size to upload zip codes and locations files

Dockerrun.aws.json, web/themes/custom/move_mil/templates/layout/html.html.twig
Also noticed that build testing artifacts made it into dev. Replacing the tag in dockerrun with production
I have…
1. Add the inclusion of the Federal DAP analytics program in a new html.html.twig file. Elliot was very concerned about loosing this data so I took the path of least resistance and just hard coded it. Ideally we follow up with a task (already in icebox) to configure this script on a per environment basis.
Load the header, check if the script is there. Also check the network tab in your browser to verify the browser has included the js script.
=> Adding the Federal DAP GA script. 

composer.json, composer.lock, config/sync/core.extension.yml, config/sync/editor.editor.basic_html.yml, config/sync/filter.format.basic_html.yml
I have…
- Address https://www.pivotaltracker.com/story/show/158796850 ticket
- Add a simple file-uploader tool to the ckeditor
1. pull changes
1. config import
1. Add a basic page and add a basic text paragraph
1. Click on the clip image and upload a file
1. Make sure the file was uploaded and visible on the page
file tool icon - https://cl.ly/1N3W1g0J442l
file uploader - https://cl.ly/3m1B0a1W0g0T
=> Add editor-file plugin to add file-uploader tool

.circleci/config.yml
This fixes #222 it should trigger a 1.x-dev build
Docker image will be built and pushed to amazon ecr
=> fixing spacing syntax

.circleci/config.yml
I have…
Deploys builds to our staging environment.
=> using python 3.6 re https://github.com/aws/aws-cli/issues/2290

composer.lock, web/.ht.router.php, web/robots.txt
So I either confused myself, or messed up a previous pr I think. I was reviewing tickets and saw that https://www.pivotaltracker.com/story/show/158390109 was almost complete, however on reviewing my local I saw that core wasn't updated. It's a quick fix so I've done the update here.
EDIT/Addtion: It made sense to update the minor contrib modules so paragraphs, entity_reference_revisions, and address and dependencies are also updated here.
I have…
This updates drupal core and dependencies to 8.5.5.
Run make composer, navigate to /admin/reports/status and verify the version number.
https://www.dropbox.com/s/6l971coqcrqdh6o/Screenshot%202018-07-18%2007.40.39.png?dl=0
=> updating drupal core to 8.5.5

.circleci/config.yml
I have…
This pull request creates a new build job for the master branch which creates the production artifact.
Head to circleci and view the build after a pr has been accepted on master. we should see the job successfully complete.
=> adding a new production build job

web/modules/custom/react_tools/tools/config/apps.js
=> IE hotfix add es6 babel polyfills in webpack

composer.lock, web/.htaccess
I have…
* Updates drupal core with the latest security release for symfony components.
* Adds www redirect for authoritative source
* Navigate to the test environments bare domain. You should be redirect to www.
* Run normal tests after verifying version on status page. No updb is needed.
=> Adding www redirect and updating drupal core

web/.htaccess
I have…
- Remove the redirection from NO www to www
- Adds redirection from www to NO www (removes the www).
1.Go to the site and test it is still up
Test env is working:
https://move-mil-test.us-east-1.elasticbeanstalk.com/ OR
https://www.move-mil-test.us-east-1.elasticbeanstalk.com/
=> Remove www redirection

web/modules/custom/react_tools/tools/apps/react-ppm-tool/src/sass/main.scss
=> fixed 3em padding issue on radio buttons

web/modules/custom/react_tools/tools/apps/react-ppm-tool/src/components/weights.js
=> fixed bad keyname for API req on ppm-tool

web/modules/custom/react_tools/tools/apps/react-ppm-tool/src/components/moveDate.js, web/modules/custom/react_tools/tools/apps/react-ppm-tool/src/components/results.js
=> fix datetime issues with ppm tool

web/modules/custom/react_tools/tools/apps/react-locator-map/src/sass/main.scss
=> fix pulse marker on locator map

web/modules/custom/react_tools/tools/config/apps.js, web/modules/custom/react_tools/tools/scripts/start.js
=> add sass watch to npm start script

Dockerrun.aws.json, docker/Dockerfile
I have…
- Updates the composer installer signature
=> Fix docker build

web/themes/custom/move_mil/js/scrollFix.js
This PR addresses [Pivotal ticket #161098469 - one broken jump link](https://www.pivotaltracker.com/story/show/161098469). The issue was too general a definition of the jump link target in the jquery logic customizing the scrolling and making the jump links more flexible. The use of a wildcard was necessary for [one other link](https://move.mil/customer-service#retirement-separation), so after tightening the primary logic, a fallback was needed to ensure that original patch remained intact.
Of course, a content change would obviate the need for that patch - the mismatched link is being generated as a custom menu item - but I can raise the point with Jared and he can decide if any edits are warranted.
I have…
- changes the jquery handling smooth jump …
=> Jump link logic fix

.ebextensions/01_nginx_proxy.config
I have…
- Add the ngnix Google maps api header. It was deployed locally, so it existed on stage.move.mil but it isn't on 1.x-dev
=> Add ngnix Google header

web/themes/custom/move_mil/images/icons/map-pulse.svg
=> add map pulse to image dir

.ebextensions/01_nginx_proxy.config
I have…
- Add Google maps images to img-src header for ngnix server configuration.
Now, I tested the change before doing the PR. And it will be all for the maps. For real.
=> So, google maps images need to be whitelisted as well

web/modules/custom/react_tools/tools/apps/react-locator-map/src/components/locatorMap.js
=> try to make icons appear in IE

config/sync/block.block.at_your_destination.yml, config/sync/block.block.during_the_move.yml, config/sync/block.block.entitlementintro.yml, config/sync/block.block.entitlementsblock.yml, config/sync/block.block.faq_section_after_the_move.yml, config/sync/block.block.faq_section_before_you_move.yml, config/sync/block.block.faq_section_delivery.yml, config/sync/block.block.faq_section_moving_day.yml, config/sync/block.block.faq_section_travel_tips.yml, config/sync/block.block.locatormapblock.yml, config/sync/block.block.move_mil_content.yml, config/sync/block.block.move_mil_help.yml, config/sync/block.block.move_mil_local_actions.yml, config/sync/block.block.move_mil_local_tasks.yml, config/sync/block.block.move_mil_page_title.yml, config/sync/block.block.prepping_the_move.yml, config/sync/block.block.reactppmtoolblock.yml, config/sync/block.block.reactweightestimatorblock.yml, config/sync/block.block.sme_advisories.yml, config/sync/block.block.sme_direct_procurement_method.yml, config/sync/block.block.sme_household_goods.yml, config/sync/block.block.sme_non_temporary_storage.yml, config/sync/block.block.sme_non_temporary_storage_retrograde_program.yml, config/sync/block.block.sme_online_education_series.yml, config/sync/block.block.sme_personal_property.yml, config/sync/block.block.sme_privately_owned_vehicles.yml, config/sync/taxonomy.vocabulary.sme_section.yml
=> Test sme config override

web/modules/custom/react_tools/tools/apps/react-locator-map/src/components/listItem.js
I have…
- Fixes validation of DSN label in location phones
- Reads from phone.field_dsn[0].value instead of just phone.field_dsn[0]
1. Pull changes
1. build react tools and clear cache
1. Review that locations, like Tinker AFB, are showing phones with the DSN label
=> Fix validation of DSN label in location phones

composer.lock
I have…
- Updates to drupal 8.6.10
=> Update to drupal 8.6.10

docker/php/php.ini
I have…
- Increase PHP memory limit from 128M to 512M
=> Increase memory limit from 128M to 512M

composer.json, composer.lock
I have…
- Update paragraph module due to SA: https://www.drupal.org/project/paragraphs/releases/8.x-1.6
1. Pull changes, clear cache and the notification should be gone
=> Update paragraph module

web/modules/custom/locations/src/Form/ManagerForm.php, web/modules/custom/locations/src/Service/Reader.php
=> added fields to ignore locations

config/sync/block.block.forums_and_workshops.yml, config/sync/block_content.type.basic.yml, config/sync/core.entity_view_display.taxonomy_term.sme_section.default.yml, config/sync/field.field.node.sme_document.field_document_file.yml, config/sync/system.menu.main.yml, config/sync/views.view.sme_section.yml, web/themes/custom/move_mil/templates/system/block/block--system-branding-block.html.twig
I have…
- Export SME configuration changes and persist them
1. Import config, new taxonomy should be visible 'Personal Property Forums and Workshops'
=> Persist SME changes

web/modules/custom/custom_move_mil_menus/custom_move_mil_menus.links.menu.yml
Code change for Pivotal ticket #164968698 - Update Nightmare Moves to Moving Stories (R.I.P. Pivotal). Note the URL slug will have to be updated on Prod/Staging for the updated menu link to work.
I have…
- Updates the `custom_move_mil_menus` module, changing the menu item associated with the `Nightmare Moves` page to reflect the requested name change to `Moving Stories`.
- Updates the item's machine name as well as the title and target path. 
- 
1. Pull code and clear cache
1. Go to `/moving-guide/nightmare-moves` and change both the page name and the custom url path to match the updates to the menu item (`/moving-guide/moving-stories`)
1. Refresh and check the updated menu item to make sure it …
=> update Nightmare Moves menu item in module to reflect new page name

composer.lock, web/modules/custom/locations/src/Service/Reader.php
I have…
- Updates Drupal
- Verify phone number is not empty when reading the XML file
Execute `drush entity-updates`
1. UPload XML file
1. Go to the locator maps tool and look for "Wright Patterson AFB"
1. You should see the results.
=> Validate phone numbers

config/sync/block_content.type.basic.yml, config/sync/views.view.faqs.yml
I have…
- Persist changes on prod for FAQ views
=> Change views names

composer.lock, web/modules/custom/react_tools/tools/package-lock.json, web/themes/custom/move_mil/package-lock.json
I have…
- Updates drupal modules.
- Updates theme libraries with vulnerabilities.
- Updates tools libraries with vulnerabilities.
1. Pull branch
1. config import
1. install and rebuild theme and tools
1. Go to the site and verify it works and looks as expected.
=> composer module and theme updates

composer.json, composer.lock, config/sync/captcha.captcha_point.contact_message_feedback_form.yml, config/sync/captcha.captcha_point.contact_message_personal_form.yml, config/sync/captcha.captcha_point.node_article_form.yml, config/sync/captcha.captcha_point.node_faq_form.yml, config/sync/captcha.captcha_point.node_location_form.yml, config/sync/captcha.captcha_point.node_page_form.yml, config/sync/captcha.captcha_point.node_sme_document_form.yml, config/sync/captcha.captcha_point.node_tutorial_form.yml, config/sync/captcha.captcha_point.user_login_form.yml, config/sync/captcha.captcha_point.user_pass.yml, config/sync/captcha.captcha_point.user_register_form.yml, config/sync/captcha.settings.yml, config/sync/core.extension.yml, config/sync/recaptcha.settings.yml
I have…
- Adds and enables Google reCaptcha on Register users and reset password forms.
1. Import config and clear caches.
1. Go to the Register users and reset password forms and you should see the captcha at the bottom.
=> Add Google re-captcha

web/modules/custom/locations/src/Form/ManagerForm.php, web/modules/custom/locations/src/Service/Reader.php, web/modules/custom/locations/src/Service/Writer.php
I have…
- Sets locations exclusion list on config
- Deletes existing locations that need to be excluded.
1. pull branch, go to locations manager.
1. add a file.
1. add an office to exclude.
1. run uploader.
1. check on content that the location is not present.
=> Save exclusions as config, delete existing ones.

web/themes/custom/move_mil/package-lock.json, web/themes/custom/move_mil/package.json
I have…
- update package.lock.json so "extend" gets updated and removes vulnerability
=> Update theme vulnerability on extend dep

config/sync/captcha.captcha_point.user_pass.yml, config/sync/captcha.captcha_point.user_register_form.yml, config/sync/field.field.node.sme_document.field_document_file.yml, config/sync/move_mil.settings.yml, config/sync/recaptcha.settings.yml, config/sync/system.theme.global.yml
I have…
- Add missing recaptcha config
- Add favicon config from production
=> Fix recaptcha

.ebextensions/post-deploy.config, Makefile
I have…
- runs a script after deploying to update database, rebuild cache and other things to do after each deploy
- removes a flag that is deprecated from the Makefile docker-compose pull command
1. can only be tested after deploying to aws
2. make another change after adding this to the eb config that would require a cache rebuild or database update to take effect
3. deploy those changes to eb
4. verify without manually running these commands that the changes took effect (the script did in fact run)
5. can also check eb log to verify that the hook occurred
6. run `make up` from the …
=> Post deploy script

composer.lock
I have…
- Updates drupal core with security patches
1. updatedb
1. entityupdate
1. config:import and clear caches
=> Update drupal to 8.6.15

.ebextensions/01_nginx_proxy.config, Dockerrun.aws.json, Makefile
I have…
- Add recaptcha headers so staging can see the widget finally
1. Tested here: https://test-move-mil.us-east-1.elasticbeanstalk.com/user/register
=> Add another recaptcha header!

.ebextensions/post-deploy.config
I have…
- added -y flag to make script non-interactive
1. deploy this to staging
2. deploy another change that would require a cache reset, menu update, etc
3. check logs that the script ran or simply that the second change correctly deployed and updated
=> added -y flag to entity-update commands

composer.lock, web/sites/default/default.settings.php
=> Update to drupal 8.7.1

composer.json, composer.lock, web/sites/default/default.settings.php
=> downgrade to drupal 8.6.16

config/sync/block.block.sme_advisories.yml, config/sync/block.block.sme_direct_procurement_method.yml, config/sync/block.block.sme_household_goods.yml, config/sync/block.block.sme_non_temporary_storage.yml, config/sync/block.block.sme_online_education_series.yml, config/sync/block.block.sme_privately_owned_vehicles.yml, config/sync/block.block.smesections.yml, config/sync/block.block.views_block__sme_section_block_13.yml, config/sync/block.block.views_block__sme_section_block_17.yml, config/sync/extlink.settings.yml, config/sync/taxonomy.vocabulary.customer_brochures.yml, config/sync/taxonomy.vocabulary.sme_section.yml, config/sync/views.view.sme_section.yml
I have…
- Add production configuration to be persisted
1. Make sure sme page is complete
=> Persist SME page configuration changes

config/sync/block.block.smesections.yml, config/sync/taxonomy.vocabulary.customer_brochures.yml, config/sync/taxonomy.vocabulary.sme_section.yml
I have…
- Adds new production configuration
=> SME configuration May-30th

web/modules/custom/react_tools/tools/package-lock.json, web/themes/custom/move_mil/package-lock.json, web/themes/custom/move_mil/package.json
I have…
- Updates node modules with high vulnerabilities.
=> Fix node vulns

CONTRIBUTING.md, post-deploy.sh
I have…
- Changes script to import configuration with drupal instead of drush to potentially avoid conflicts.
1. Run the script and check that it runs successfully.
=> updated config import command to use drupal not drush

web/modules/custom/react_tools/tools/apps/react-locator-map/src/components/listItem.js, web/modules/custom/react_tools/tools/apps/react-locator-map/src/sass/main.scss
=> mobile friendly table for locator tool

docker/Dockerfile, docker/nginx.conf, docker/supervisord.conf
I have…
- Changes supervisord settings to improve php-fpm and nginx 
- Increases buffersize and timeouts for php-fpm
1. create new docker image/container
2. verify site works normally
3. verify drush commands work normally
=> Post nginx conv

docker/nginx.conf
I have…
- Attempts to block certain malicious requests
1. Run test for VDP vulnerability
=> check for two http header fields to reject

composer.lock, web/modules/custom/parser/src/Command/ParserCommand.php, web/modules/custom/parser/src/Controller/DiscountsController.php, web/modules/custom/parser/src/Controller/EntitlementsController.php, web/modules/custom/parser/src/Controller/LocationsController.php, web/modules/custom/parser/src/Controller/PpmEstimatorController.php, web/modules/custom/parser/src/Controller/Rates400NGController.php, web/modules/custom/parser/src/Controller/Zip3Controller.php, web/modules/custom/parser/src/Controller/Zip5Controller.php, web/modules/custom/parser/src/Controller/ZipcodesController.php, web/modules/custom/parser/src/Service/DbReader.php, web/modules/custom/parser/src/Service/DbWriter.php, web/modules/custom/parser/src/Service/LocationWriter.php, web/modules/custom/parser/src/Service/RouteDistance.php, web/modules/custom/react_tools/tools/package-lock.json, web/themes/custom/move_mil/package-lock.json, web/themes/custom/move_mil/package.json
=> Update npm libraries

composer.json, composer.lock, web/sites/default/default.settings.php
=> Update to Drupal 8.7.5

web/modules/custom/react_tools/tools/apps/react-ppm-tool/src/App.js, web/modules/custom/react_tools/tools/apps/react-ppm-tool/src/components/results.js, web/modules/custom/react_tools/tools/apps/react-ppm-tool/src/sass/main.scss, web/modules/custom/react_tools/tools/apps/react-weight-estimator/src/sass/main.scss
=> change print css options for ppm tool and weight estimator

.ebextensions/01_nginx_proxy.config
I have…
- fixes an indent issue causing invalid yaml
1. build image 
2. deploy to aws successfully
=> fixed indent issue causing invalid yaml syntax

web/modules/custom/locations/src/Service/Reader.php
I have…
- Adds area code to CNSL Commercial phone numbers if available.
1. Upload a locations file.
1. Go to locator map and look for a location with area code like 'Naval Support Activity Deveselu'
1. The area code will appear as part of the phone number.
=> add Area Code if CNSL, Comm, and available.

config/sync/system.menu.main_menu.yml, config/sync/system.menu.moving_guide.yml, config/sync/system.menu.resources.yml, web/modules/custom/custom_move_mil_menus/custom_move_mil_menus.links.menu.yml
I have…
- changed the Retirees/Separatees link to read Retiring/Separating so the link is properly displayed to all end users.
=> Change moving-guide menu item. Add Customer Brochures to menu config

Makefile, post-deploy.sh, web/modules/custom/custom_move_mil_menus/custom_move_mil_menus.links.menu.yml
=> Remove Customer Brochures from module

composer.lock
I have…
-Updates drupal to 8.7.6
=> Update to drupal 8.7.6

config/sync/core.menu.static_menu_link_overrides.yml, config/sync/system.menu.main_menu.yml, config/sync/system.menu.moving_guide.yml, config/sync/system.menu.resources.yml, docker/php/php.ini
I have…
- persist config on menu 2019-08-21
- set PHP memory limit back to 512M
=> Persist config

Makefile, web/themes/custom/move_mil/js/slider.js
=> Remove nav items scroll to improve site accessibility & UX

web/modules/custom/react_tools/tools/apps/react-locator-map/src/components/listItem.js, web/modules/custom/react_tools/tools/apps/react-ppm-tool/src/App.js, web/modules/custom/react_tools/tools/apps/react-ppm-tool/src/components/locations.js, web/modules/custom/react_tools/tools/apps/react-ppm-tool/src/components/results.js, web/modules/custom/react_tools/tools/apps/react-ppm-tool/src/sass/main.scss
=> css fixes on some of the tools for mobile issues

Makefile, config/sync/system.menu.main_menu.yml, config/sync/system.menu.moving_guide.yml, config/sync/system.menu.resources.yml, web/modules/custom/custom_move_mil_menus/custom_move_mil_menus.links.menu.yml
=> Feature 167257471/update menu

composer.json, docker-compose.yml, tests/features/bootstrap/FeatureContext.php, tests/features/ppm.feature, web/modules/custom/custom_move_mil_menus/custom_move_mil_menus.links.menu.yml, web/modules/custom/parser/src/Controller/PpmEstimatorController.php, web/modules/custom/react_tools/tools/apps/react-ppm-tool/src/components/results.js
=> Remove PPM estimator changes

docker/php/php.ini, post-deploy.sh
=> Increase php memory limit

web/themes/custom/move_mil/templates/layout/page.html.twig
=> change ETA to Electronic Transportation Acquisition for testing

composer.json, composer.lock, docker-compose.yml, web/modules/custom/parser/src/Service/ExcelReader.php
=> Rewrite excel reader so it doesn’t fail if the file has stray data

.circleci/config.yml
=> Remove docker layer caching for circle ci building

Dockerrun.aws.json, web/themes/custom/move_mil/templates/layout/page--front.html.twig
=> Change eta fullname

web/modules/custom/locations/src/Service/Writer.php
I have…
- Add 3 tries on the geolocation of the offices when reading the uploaded XML file.
1. Upload a file.
1. Make sure the offices are geolocated.
=> Try 3 times to geolocate each office when unsuccessful

tests/features/ppm.feature, web/modules/custom/parser/src/Controller/PpmEstimatorController.php
I have…
- Make ranges after the total has the PPm incentive applied.
1. Test against Julie's example.
=> Change min max ranges

tests/features/ppm.feature, web/modules/custom/parser/src/Controller/PpmEstimatorController.php, web/modules/custom/react_tools/tools/apps/react-ppm-tool/src/components/results.js
=> Use random num to generate ranges and format results

.circleci/config.yml, composer.json, composer.lock, config/sync/core.extension.yml
I have…
- Update to Drupal 8.8.1
=> Update to drupal 8.8.1

config/sync/block.block.forums_and_workshops.yml, config/sync/block.block.reactppmtoolblock.yml, config/sync/block.block.sme_advisories.yml, config/sync/block.block.sme_household_goods.yml, config/sync/block.block.sme_non_temporary_storage.yml, config/sync/block.block.sme_online_education_series.yml, config/sync/block.block.sme_personal_property.yml, config/sync/block.block.sme_privately_owned_vehicles.yml, config/sync/block.block.views_block__sme_section_block_13.yml, config/sync/block.block.views_block__sme_section_block_18.yml, config/sync/views.view.sme_section.yml
=> Persist configuration 12-30-2019

.circleci/config.yml
=> Fix circle ci config for production

web/modules/custom/react_tools/tools/apps/react-ppm-tool/src/components/results.js, web/modules/custom/react_tools/tools/apps/react-ppm-tool/src/sass/main.scss
=> formatting of results on ppm

web/modules/custom/parser/src/Controller/PpmEstimatorController.php, web/modules/custom/parser/src/Service/DbReader.php
=> Apply discount only to linehaul rate, packing, and shorthaul rate

Dockerrun.aws.json, web/modules/custom/locations/src/Service/Writer.php
=> Fix missing phone area

config/sync/views.view.sme_section.yml
=> persist changes on sme 2020/01/29

.circleci/config.yml, web/themes/custom/move_mil/templates/content/search-result--search-exclude-node-search.html.twig
=> Clear cache after cim on behat testing

config/sync/block.block.coronavirus.yml, config/sync/block.block.homepageheroimage.yml, config/sync/block.block.mainmenu.yml, config/sync/block.block.move_mil_account_menu.yml, config/sync/block.block.move_mil_branding.yml, config/sync/block.block.move_mil_login_banner.yml, config/sync/block.block.move_mil_main_menu.yml, config/sync/block.block.reactppmtoolblock.yml
=> Add coronavirus banner (block config)

composer.lock, config/sync/block.block.reactppmtoolblock.yml, web/modules/custom/custom_move_mil_menus/custom_move_mil_menus.links.menu.yml, web/modules/custom/movemil_helper/movemil_helper.module
=> Add PPQRG menu link

web/modules/custom/parser/src/Controller/PpmEstimatorController.php
I have…
- Fix what 400NG Year the PPM tool needs to use if the moving date is before May 15th
=> Include first 15 days of May

web/modules/custom/custom_move_mil_menus/custom_move_mil_menus.links.menu.yml, web/modules/custom/react_tools/tools/build/service-worker.js, web/modules/custom/react_tools/tools/package-lock.json, web/modules/custom/react_tools/tools/package.json, web/themes/custom/move_mil/package-lock.json, web/themes/custom/move_mil/package.json
I have…
- Update react tools node libraries
-Update theme node libraries
- Update menu item
=> Make menu changes

Dockerrun.aws.json, web/modules/custom/custom_move_mil_menus/custom_move_mil_menus.links.menu.yml, web/themes/custom/move_mil/scss/02-molecules/_block-move-mil-login-banner.scss, web/themes/custom/move_mil/templates/system/block/block--covid19faq.html.twig
I have…
- Add new twig template for covid19 block
-Add css for covid19 block
=> Change covid block

composer.json, composer.lock
I have…
- Updates Drupal from 8.7.5 to 8.9.1
1. Run composer install
- For local testing, you may need to delete the /vendor directory if you run into problems running composer install
2. Run drush updb
3. Run drush cr
=> CF: Updte drupal core to 8.9.1

CONTRIBUTING.md
I have…
- _Document the Drupal part of the deployment._
=> add drupal doc for the deploy

CONTRIBUTING.md
Update instructions for cloning the repo in CONTRIBUTING.MD.
=> Update git repo reference from Bixal to Transcom

.github/dependabot.yml
This will add daily updates to PHP, Docker, and Node.
=> Add explicit dependabot config

docker/Dockerfile
=> update sass to 1.26.10

.envrc
This will allow aws-vault commands to work seamlessly with this repo
=> add .envrc with AWS_VAULT_KEYCHAIN_NAME set to login

Dockerrun.aws.json, docker-compose.yml, docker/Dockerfile, docker/supervisord.conf
Based on these docs https://github.com/nginxinc/docker-nginx/blob/master/stable/alpine/Dockerfile#L104-L106
I think this will do the thing.
=> MB-4344 | Forwarding Nginx logs to Docker log collector

docker/Dockerfile
Reverts transcom/move.mil#854
This will break things. I should not have merged it.
=> Revert "Bump php from 7.4-fpm-alpine3.13 to 8.0.5-fpm-alpine3.13 in /docker"
