transcom/move.mil

- web/themes/custom/move_mil/scss/03-organisms/_paragraph--text-with-image.scss
- web/themes/custom/move_mil/templates/system/paragraph/paragraph--text-with-image.html.twig
I have…
- updates the classes in our template and partial to include 
usa-media_block
usa-media_block-body
usa-media_block-img
1. Pull these changes locally
2. in the custom theme directory, npm run build
3. create a new basic page content
4. give it a title
5. add the Text w/Image Paragraph
**Test A**
- give it a title
- include a logo w/alt text
- set image alignment to left
- include markup in the WYSIWYG editor
- paragraph
- unordered list of external links
should still match the previous look and functionality
> updated our classes to be more america(usa)

- web/themes/custom/move_mil/config/javascript.js
- web/themes/custom/move_mil/config/sass.js
- web/themes/custom/move_mil/package-lock.json
- web/themes/custom/move_mil/package.json
I'm not seeing a ticket in Pivotal yet, but this PR contains implementation of some behind-the-scenes gulp/npm script refinements @scottqueen-bixal and I discussed earlier today.
I have…
- Switches the javascript linter from eslint (which was breaking) to jshint, which works better with jquery
- Adds sass and js linting into the watch process, so they run automatically when a change is made in and before build.
1. pull code
1. navigate to the theme root and run `npm install`
1. run `npm run watch` and follow the processes as they execute in the terminal
1. make a sass change (or just save one of the partials). The sass linter should run again before the css build.
1. make a change to one of the …
> Linter refinements

- web/themes/custom/move_mil/scss/02-molecules/_paragraph--pro-tip.scss
- web/themes/custom/move_mil/templates/system/paragraph/paragraph--pro-tip.html.twig
I have…
- updates our left/right alignments to use usa-one-third class rather than 35%
- removes usa-media-block as a parent class
- and sets alignment based on the selected value in the admin content form
1. Pull these changes locally
2. cd /move-mil/web/themes/custom/move_mil
3. npm run build
4. create a basic page with varying pro-tips(selected alignments) and basic-text paragraphs to mimic the following view
> updated our protip alignment field, template, and  styles partial

- web/themes/custom/move_mil/scss/02-molecules/_paragraph--type--tabular-data.scss
- web/themes/custom/move_mil/templates/system/field/field--paragraph--field-table-image-title--tabular-data.html.twig
- web/themes/custom/move_mil/templates/system/paragraph/paragraph--tabular-data.html.twig
Executes Pivotal ticket https://www.pivotaltracker.com/story/show/156471638
I have…
- Refactors template for tabular data paragraph to make it an HTML table, somewhat matching live site. However, the table only covers a single paragraph, which in turn covers a *row* of the table. We might need to revisit this setup in a future sprint.
- Integrates tablular data styles used in live site.
1. pull code
1. run `npm run build` from theme folder to compile css updates
1. go to "/entitlements" in local environment to verify theming
Local environment with implemented theming:
> initial templating and styles for SINGLE tabular data paragraph

- config/sync/field.field.node.page.field_paragraph.yml
Triage from merge conflicts this morning. Corrects which paragraph types should be allowed in that field on basic pages.
I have…
- Adds tabular data wrapper and removes tabular data from allowed paragraph types that can be added on basic pages.
1. Pull code and import config
1. Go to your local and try to add a tabular data item on the Entitlements page.
> Paragraphs config cleanup to unbreak tabular data

- web/themes/custom/move_mil/scss/01-atoms/_blockquote.scss
- web/themes/custom/move_mil/scss/01-atoms/_jump-link-section-divider.scss
- web/themes/custom/move_mil/scss/01-atoms/_nightmare-moves-title-icons.scss
- web/themes/custom/move_mil/scss/04-pages/_nightmare-moves.scss
We're going to need to revisit cases where sections and their dividers aren't so neatly tied to jump links, not to mention cases where the jump links currently differ from the live site.
But going with a general rule that the sections delineated by jump links have a light gray divider between them, the contents of this PR should be able to cover much of the spacing between/around page sections.
I have…
- Except for the first paragraph on the page, puts 20px padding, 1px border (aka the section divider) and 20px margin above the title fields of Basic Text paragraphs (the specific fields referenced in the jump links module). 
- Creates a special snowflake override to mimic the divider behavior on the Nightmare Moves page, which has Basic Text and Pro …
> Section dividers (tied to jump link targets)

- config/sync/block.block.at_your_destination.yml
- config/sync/block.block.during_the_move.yml
- config/sync/block.block.faq_section_after_the_move.yml
- config/sync/block.block.faq_section_before_you_move.yml
- config/sync/block.block.faq_section_delivery.yml
- config/sync/block.block.faq_section_moving_day.yml
- config/sync/block.block.faq_section_travel_tips.yml
- config/sync/block.block.jumplinks.yml
- config/sync/block.block.move_mil_content.yml
- config/sync/block.block.move_mil_tools.yml
- config/sync/block.block.prepping_the_move.yml
- web/themes/custom/move_mil/scss/01-atoms/_back-to-top.scss
- web/themes/custom/move_mil/scss/02-molecules/_breadcrumbs.scss
- web/themes/custom/move_mil/scss/02-molecules/_login-banner.scss
- web/themes/custom/move_mil/scss/03-organisms/_block-jumplinks.scss
- web/themes/custom/move_mil/scss/03-organisms/_left-sidebar-layout.scss
- web/themes/custom/move_mil/scss/03-organisms/_uswds-middle-section.scss
- web/themes/custom/move_mil/templates/layout/page.html.twig
- web/themes/custom/move_mil/templates/system/block/block--jumplinks.html.twig
- web/themes/custom/move_mil/templates/system/region/region--sidebar-first.html.twig
Adds sign-in banner to interior pages and makes breadcrumb treatment more responsive. @scottqueen-bixal is adding the banner on the front page in a different PR.
I have…
- Adds sign-in banner to interior pages
- makes breadcrumb treatment more responsive.
Desktop width:
Mobile width (no banner, shaded background on breadcrumbs):
> Build sign in banner

- web/themes/custom/move_mil/scss/02-molecules/_paragraph--callout-accordion.scss
- web/themes/custom/move_mil/templates/system/paragraph/paragraph--callout-accordion.html.twig
I have…
- accordion content was wrapped in the <button/> element and was performing native functionality to close based on the aria target. The work here corrects that by separating out the content to a different div and passing through specificity to the aria control id from our paragraphs
**Old behavior**
**New behavior**
1. pull locally
2. npm run build at the theme level
3. make cr
4. create custom paragraph block with callout accordion and basic text content (include a link)
5. place in second region <front>
6. navigate to the homepage
7. set window size to less than 900px
8 interacting with the accordion should behave has outlined above.
> updated styles and and template structure to set <button> and aria control to callout accordion by usa-accordion-content-pid

- config/sync/views.view.comment.yml
- config/sync/views.view.comments_recent.yml
- config/sync/views.view.content_recent.yml
- config/sync/views.view.frontpage.yml
- config/sync/views.view.who_s_new.yml
- config/sync/views.view.who_s_online.yml
- web/themes/custom/move_mil/templates/content/node--tutorial.html.twig
I have…
- disables unused views
2. make cim
3. make cr
4. navigate to /admin/structure/views
ensure that only the following views are enabled
- content
- custom block library
- FAQs
- Files
- People
- Taxonomy term
- Watchdog
admin view after CONFIG import
> Feature 156691172 clean views listing

- web/sites/default/settings.php
I have…
Changes the order in which settings.local.php gets loaded (we should load this file at the end)
See if everything still works?
> Moved code block to load settings.local.php to the end of the file

- composer.json
- composer.lock
- config/sync/core.extension.yml
- config/sync/editor.editor.full_html.yml
- config/sync/filter.format.full_html.yml
- config/sync/wysiwyg_template.settings.yml
- config/sync/wysiwyg_template.wysiwyg_template.1_4_column_layout.yml
- config/sync/wysiwyg_template.wysiwyg_template.2_3_column_layout.yml
- config/sync/wysiwyg_template.wysiwyg_template.2_col.yml
- config/sync/wysiwyg_template.wysiwyg_template.3_column_layout.yml
- web/themes/custom/move_mil/scss/01-atoms/_cke-columns.scss
- web/themes/custom/move_mil/scss/01-atoms/_content-columns.scss
I have…
- adds/enables a new module to work with the WYSIWYG API and creates 4 templates in the CKeditor, including;
- 1/2 Column layout 
- 1/3 column layout 
- 1/4 column layout 
- 2/3 column layout
1. pull code locally
2. make composer
3. cd /move-mil/web/themes/custom/move_mil
4. npm run build
5. make cr
6 navigate to a "basic page" content type, ie. /moving-guide
7. edit the node and add a basic text paragraph type
8. select "Full HTML"
9. in the upper right hand side of the CKeditor select the template button 
10. select one of the content-column templates
11. replace placeholder content with new content, save 
here is the content within tabular data updated with this new implementation and an …
> Feature 157232981 implement ckui module in wysiwyg

- web/themes/custom/move_mil/templates/layout/page--front.html.twig
This is a very simple fix........just adapting one last set of hardcoded jump links, this one with the targets entered into the home page template, to reference semantic paragraph ids. It'd be great to get this integrated within this sprint, if possible.
I have…
-Edits four jump link paths in the home page template to match new paragraph ids
1. Pull code and import config
1. Open homepage in mobile view
1. Click on each of the four jump link icons to test functionality
> adapt mobile homepage jumplink targets to prettified target ids

- web/themes/custom/move_mil/scss/01-atoms/_content-columns.scss
- web/themes/custom/move_mil/scss/01-atoms/_text-formatted.scss
- web/themes/custom/move_mil/scss/02-molecules/_field--name-field-paragraph.scss
- web/themes/custom/move_mil/scss/02-molecules/_paragraph--callout-accordion.scss
- web/themes/custom/move_mil/scss/02-molecules/_paragraph--type--basic-text.scss
- web/themes/custom/move_mil/scss/03-organisms/_uswds-middle-section.scss
- web/themes/custom/move_mil/scss/04-pages/_customer-service.scss
- web/themes/custom/move_mil/scss/04-pages/_nightmare-moves.scss
- web/themes/custom/move_mil/scss/04-pages/_page--front.scss
- web/themes/custom/move_mil/scss/04-pages/_tools-resources.scss
- web/themes/custom/move_mil/scss/_variables.scss
This pull request fully addresses Pivotal bug tickets [157849916 - standardize spacing below page title, broader scope than originally intended](https://www.pivotaltracker.com/story/show/157849916) and [157775887 - section dividers on Nightmare Moves page](https://www.pivotaltracker.com/story/show/157775887). It also *mostly* addresses [157847858 - spacing on some WYSIWYG two-column lists](https://www.pivotaltracker.com/story/show/157847858), and I recommended one or two slight content changes to wrap that one up.
The first story in particular will require ample testing and potentially some back-and-forth, so the sooner we can get it merged into the staging site, the better.
I have…
- Adds 20-25px of padding above the paragraphs wrapper field in ALL …
> A bunch of global spacing/layout/alignment triage

- web/themes/custom/move_mil/js/scrollFix.js
- web/themes/custom/move_mil/js/stickyBackToTopButton.js
- web/themes/custom/move_mil/scss/01-atoms/_back-to-top.scss
- web/themes/custom/move_mil/scss/_variables.scss
- web/themes/custom/move_mil/templates/system/paragraph/paragraph--text-with-image.html.twig
Main purpose of this PR is to address Pivotal bug tickets [157850939 - Back To Top button not scrolling in IE](https://www.pivotaltracker.com/story/show/157850939) and [157847898 - Back To Top button appearing over mobile menu](https://www.pivotaltracker.com/story/show/157847898). It also adds smooth scrolling to the Back to Top button (not covered in Pivotal) and follows through with additional cleanup associated with [image positioning on certain paragraphs](https://www.pivotaltracker.com/story/show/157485059) and [general spacing issues at or near the top of the main content area](https://www.pivotaltracker.com/story/show/157849916).
I have…
- Uses jQuery, including two constantly-running window listeners, and css `position: fixed` to functionally …
> Back To Top button refactor and a couple other cleanup tweaks

- web/modules/custom/custom_move_mil_menus/custom_move_mil_menus.links.menu.yml
This PR executes Pivotal ticket [157847990 - "Tutorial" main navigation item needs to be pluralised](https://www.pivotaltracker.com/story/show/157847990). It simply adds an "s" onto the "Tutorial" item's text in the menu links yml file to make it "Tutorials".
I have…
- See above
1. Pull code
1. Update the `custom_move_mil_menus` module if needed
1. See the update in the main nav menu
> Simple text edit in menu module

- web/themes/custom/move_mil/scss/01-atoms/_links.scss
- web/themes/custom/move_mil/scss/02-molecules/_paragraph--customer-service-box.scss
I have…
- add global word break for <a> tags
- making sure our links in service box break all do not extend outside div
2. at the theme root, npm run build
3. make cr
4. navigate to /service-specific-information and ensure that the changes are working as expected across browsers.
**Firefox**
**IE**
**Safari**
> Feature 157776405 wordbreak links cross browsers

- web/themes/custom/move_mil/scss/02-molecules/_paragraph--type--tabular-data-wrapper.scss
I have…
- updates the styles of tabular data paragraph types to prevent overflow of content at mobile
2. at the theme root, npm run build
3. navigate to /entitlements
4. check across browsers, including ie that all tabular cells are now responsive with proper margins
**updated view on ie11 win10**
> new styles at mobile breakpoint to prevent overflow at mobile

- config/sync/field.storage.paragraph.field_protip_alignment.yml
I have…
- removes the float values so users will no longer be able to select L | R for pro-tip paragraph alignment, only Top | Bottom
2. navigate to Home >Administration >Structure >Paragraphs types >Pro tip >Manage fields > Protip_alignment
3. you should no longer see the following values
**float left | left
float left | right**
> CONFIG | removing our floated field values

- web/themes/custom/move_mil/scss/04-pages/_nightmare-moves.scss
Re-does [very simple previous commit](https://github.com/Bixal/move.mil/pull/150/commits/c9fe705630ebcd5c53ed35ec1c11b329ebe5df45) from last sprint that was inadvertently wiped away last week.
I have…
- Adds position: relative back into nightmare moves page so dividers don't go full width
1. Pull code
1. compile theme assets
1. Go to nightmare moves page (NOT LOGGED IN) and make sure section dividers do not extend beyond the main text area.
Fixed on local:
> TRIAGE: put position relative back on nightmare moves article wrapper

- web/themes/custom/move_mil/scss/03-organisms/_usa-footer-secondary_section.scss
- web/themes/custom/move_mil/scss/03-organisms/_usa-header-extended.scss
- web/themes/custom/move_mil/scss/04-pages/_page--front.scss
This PR set static heights on logos in header, footer and home page service-specific section because Internet Explorer's continued existence at this point is almost entirely dependent on Microsoft's marketing to stolid, risk-averse institutions that are afraid of adaptation to accommodate the proliferation of things that work.
I have…
- Sets fixed heights on three instances where logos are stretching to their original heights despite conforming to set widths on IE11 in older versions of Windows.
- Specifically, fixes this issue in the Transcom logos in the header and footer on all pages, and the five service-specific icons at the bottom of the home page. 
1. Pull code
1. Compile theme assets
1. …
> Internet Explorer is a flaming dumpster fire of a browser

- Makefile
- web/themes/custom/move_mil/backstop-paths.js
I have…
- updates our backstopjs paths array to include all current urls as of Friday, June 15, 2018
- includes a new make build-tools command for building our react tools
**validate backstop testing**
1. update local with the latest DB, Files, Code, and Config
2. from the theme root, npm run vis-ref to create the reference images from stage
3. from the theme root, npm run vis-test to create the test images from your local and compare to stage
4. you should be able to pass all test currently
**validate make command**
1. from the project root, run make build-tools
2. to confirm, navigate to each tool directory and ensure that 
- the node_modules have been installed
- the local css directory and css …
> Updates to vis-testing 

- composer.json
- composer.lock
- config/sync/core.extension.yml
I have…
- installs admin_toolbar with composer and updates the enabled configuration for the module features to allow easy access to built-in Drupal tools like "clear cache."
2. make cim
3. make cr
4. make uli
5. login
6. check to see that the following modules are enabled
- Admin Toolbar
- Admin Toolbar Extra Tools
- Admin Toolbar Links Access Filter
if you filter by key work "Admin Toolbar" you will get a result that looks like this
you should also be able to select the Drupal 8 icon to flush all caches...
> installed and enabled admin_toolbar module

- web/modules/custom/react_tools/tools/react-weight-estimator/src/components/total.js
- web/modules/custom/react_tools/tools/react-weight-estimator/src/sass/main.scss
Residual issues with weight estimator cleaned up.
I have…
- Puts the fixed total bar in the weight estimator into a usa-grid to ensure it aligns with rest of content.
- Completes last step needed to properly align weight estimator columns in IE10
1. Pull code
1. Build tools
1. Check tools in priority browsers (and IE10)
> fully vetted IE grid alignment in weight estimator tool

- .ebextensions/01_nginx_proxy.confg
This will fix errors related to uploading the larger ( <=3mb ) files for the parser. The nginx proxy which controls the connection to the load balancer to our php docker service was limiting that connection. There was a secondary config within drupal that also needs to be updated to fix this issue but this should clear it up on the ec2 side of things.
Head to the admin parser and upload a larger than 3 mb. A drupal error, or no error should happen. Nginx should not be the limiter here.
https://bixal365-my.sharepoint.com/personal/ivonne_carrillo_bixal_com/Documents/Microsoft%20Teams%20Chat%20Files/Screen%20Shot%202018-07-12%20at%2010.56.50%20AM.png
> adding a max body size value to our nginx proxy 

- config/sync/block.block.during_the_move.yml
PR to persist config changes already on live site. Completes Pivotal ticket [#158525798 - clean up "During the Move" jump link on Moving Tips page](https://www.pivotaltracker.com/story/show/158525798)
I have…
- Unchecks the "Override title" box in the "FAQs: Moving Tips Block - During the Move" block settings.
1. Pull code
1. check the id on the second moving tips block wrapper. It should match that on the live site, `during-the-move-packing-and-unloading`. The jump link itself will not be updated though - that is content.
Local with change:
> config change for cleaned jump link

- .circleci/config.yml
I have…
This pull request creates a build step to build and push our docker image to aws ecr automatically on 1.x-dev merges
To verify the changes proposed in this pull request this pull request should trigger the 4th build job.
> Circleci now builds the staging artifact on the 1.x-dev branch

- web/modules/custom/parser/src/Form/FilesAndTablesManagerForm.php
I have…
- For the custom form that we implemented to upload/parse PPM and Locator files, the /tmp location is not optimal on stage and production. Because we have at least 2 instances and the file will be uploaded only to one instance, causing intermittent 'file not found' errors. So now, the file location will be the public /sites/default/files, that is share for all the resources,
- the change is only in that form /admin/config/parser/manager
1. Pull changes
1. clear caches
1. go to  /admin/config/parser/manager
1. upload a file and submit several times, of different types.
1. The …
> Fix PPM and Locations files parser tmp path

- web/modules/custom/parser/src/Controller/PpmEstimatorController.php
I have…
- Changes the query to the zip5 table. Instead of fetching the column `rate_area` which does not exist, now it is fetching the correct column name `service_area`.
- Cast to float the pack and unpack array values instead of the array. Casting the array to float is making the array null. Then the pack and unpack values are equal to 0. That was clearly a mistake, I meant to cast the values from the array. It's fixed now.
1. pull branch changes and clear caches.
1. Use the PPM tool with the following data
```
{
"selectedEntitlement": "o-3-w-3",
"isDependencies": true,
"locations": …
```
> Use zip5 ‘service_area’ column name instead of wrong one ‘rate_area’

- config/sync/block.block.jumplinks.yml
I have…
- Address pivotal ticket https://www.pivotaltracker.com/story/show/159927157
- adjust the configuration of the jumplink block display -- it was displaying on the service specific information pages, and we did not want that.
1. pull changes and clear caches
1. import configuration
1. go to the site as an admin user
1. go to Structure -> Block layout
1. go to jumplinks config 
1. select restricted pages, and `service specific information pages` should be there
> Remove jumplinks block on Service Specific Information pages

- web/themes/custom/move_mil/preprocess/block/block__system_branding_block.preprocess.inc
- web/themes/custom/move_mil/templates/system/block/block--system-branding-block.html.twig
Executes [Pivotal ticket #159407375 - different site title/subtitle on SME page vs. other pages](https://www.pivotaltracker.com/story/show/159407375).
I have…
- Adds a preprocess exposing the node id to the block containing the site title/slogan
- Leverages that node id within a new block template to generate the slogan conditionally based on the value of that node id
1. Pull code, clear cache
1. Go to `/sme` to see the new subtitle `Official DoD PPSO & TSP Moving Portal`
1. Go to any other page to see the updated subtitle `Official DoD Customer Moving Portal`
[See ticket for screenshots.](https://www.pivotaltracker.com/story/show/159407375)
> preprocess and template for conditional site slogan for SME page

- config/sync/block.block.move_mil_login_banner.yml
Simple PR......ensures changes to the login banner per https://www.pivotaltracker.com/story/show/160450775 will persist upon future deployments. Change made in consultation with @ivonne-gov.
I have…
- Integrates config related to the newly-created Login Banner Block from the production site (via a db dump and partial export) into the code base.
- A previous commit/PR had created this block, but it did not match settings for new blocks when created and placed on the staging or prod sites, so an error resulted and had to be fixed on each.
(probably not needed, but.....)
1. Pull code
1. Import production db
1. The block in question should look identical to the [live …
> fix login banner config to match prod site

- config/sync/field.field.node.location.field_location_address.yml
- web/modules/custom/react_tools/tools/apps/react-locator-map/src/components/listItem.js
This PR primarily fixes a heretofore unnoticed bug that was hiding the first line of addresses from locations in Locator Map results. 
I have…
- Changes the address field name in the ListItem partial to address1, matching the correct format
- Makes the comma after the first address field conditional upon existence of text in the second address field. Also does the same with the comma between city and state, but this should not have a functional effect since state is required.
1. Pull code, build React tool assets
1. Search for any valid location. Ex: "New London"
1. Each result item should contain full addresses including a street name, and commas should never be at the end of a line.
Live site …
> Location address fixes on locator map

- config/sync/core.entity_form_display.node.sme_document.default.yml
- config/sync/core.entity_view_display.node.sme_document.default.yml
- config/sync/core.entity_view_display.node.sme_document.teaser.yml
- config/sync/field.field.node.sme_document.field_document_id.yml
- config/sync/field.storage.node.field_document_file.yml
- config/sync/field.storage.node.field_document_id.yml
- config/sync/views.view.sme_section.yml
- web/themes/custom/move_mil/preprocess/node/node__sme_document__teaser.preprocess.inc
- web/themes/custom/move_mil/scss/03-organisms/_view-sme-section.scss
- web/themes/custom/move_mil/templates/system/view/node--sme-document--teaser.html.twig
Continues work on Pivotal story [#161923738 - new dynamic SME page](https://www.pivotaltracker.com/story/show/161923738).
I have…
- Converts the Document ID field from a number field to a more flexible text field
- Adds a node preprocess to display the document file size in a more friendly format
- Reworks the relevant document template file and related scss file to make item theming match preliminary specs 
- Adds a pager to each SME section block appearing on the landing page
1. Pull code, import config and rebuild theme css
1. IF YOU HAVEN'T YET: Create new Basic page with custom url `/sme-page`; add SME Section taxonomy terms; create corresponding Menu items; add documents to test.
1. Add >10 …
> Further development of new SME page

- config/sync/block.block.smesections.yml
- config/sync/field.field.node.sme_document.field_document_archive_date.yml
- web/modules/custom/custom_move_mil_menus/custom_move_mil_menus.links.menu.yml
Getting a few minor pov/sme related config changes into code base and up to staging. The most notable is adding the menu link to the POV page, as directly requested by client. 
I have…
> Add menu link to POV page and make document archive date field optional

- config/sync/block.block.faq_section_pov_shipments.yml
- config/sync/views.view.faqs.yml
Simple config to get the POV-related FAQ items requested by the client wired up.
I have…
- Creates a new display within the FAQ view, filtering FAQ items by the new POV Shipments taxonomy term.
- Places the block within the Content section of block layout, immediately after the rest of the FAQ page blocks, and restricts it to appearing on the `/faqs` and `/pov` paths.
1. Pull code and db
1. Create one or more FAQ items and tag each one with the POV taxonomy term
1. Each item should appear as an accordion item in a new section on both the FAQ and POV pages
Partially-built section (local):
> create POV block in FAQs view and place it on FAQ and POV pages

- .ebextensions/01_nginx_proxy.config
- config/sync/block.block.faq_section_pov_shipments.yml
- config/sync/views.view.faqs.yml
I have…
Creates a new display within the FAQ view, filtering FAQ items by the new POV Shipments taxonomy term.
Places the block within the Content section of block layout, immediately after the rest of the FAQ page blocks, and restricts it to appearing on the /faqs and /pov paths.
Pull code and db
Import config
Create one or more FAQ items and tag each one with the POV taxonomy term
Each item should appear as an accordion item in a new section on both the FAQ and POV pages
> New POV block view in FAQ page

- config/sync/views.view.sme_section.yml
This PR takes care of Pivotal ticket [#163332884 - Adjust SME view configuration (Advisories) to sort by Document ID (descending)](https://www.pivotaltracker.com/story/show/163332884)
I have…
- Edits the SME Section view config covering the Advisories block to add a supplemental sort by Document ID.
- Does the same for the Archive Advisories block, though we're not using that view display anywhere at present.
1. Pull code/db/files
1. Go to `/sme` and scroll to Advisories. Order should match that in the screenshot below.
Local with fix:
> re-sort SME advisories by document ID (descending)

- config/sync/views.view.sme_section.yml
This PR deals with [Pivotal ticket #163625801](https://www.pivotaltracker.com/story/show/163625801). It sort all non-advisories SME sections by alphabetical order and (as a bonus while I was at it) hides empty SME section blocks to avoid the appearance of a stray section title with nothing below it.
I have…
- See description above
1. Pull code and import config
1. Go to `/sme`. All sections except for Advisories should now be sorted alphabetically.
Example section with new sort (local):
> SME alphabetical sort

- config/sync/core.entity_form_display.node.sme_document.default.yml
- config/sync/core.entity_view_display.node.sme_document.default.yml
- config/sync/core.entity_view_display.node.sme_document.teaser.yml
- config/sync/field.field.node.sme_document.field_document_file.yml
- config/sync/field.field.node.sme_document.field_external_link.yml
- config/sync/field.storage.node.field_external_link.yml
- web/themes/custom/move_mil/preprocess/node/node__sme_document__teaser.preprocess.inc
- web/themes/custom/move_mil/scss/03-organisms/_view-sme-section.scss
- web/themes/custom/move_mil/templates/system/view/node--sme-document--teaser.html.twig
Adds a Link field to SME Document content type and integrates it into the view mode for SME page items. Per Pivotal ticket [#164245943](https://www.pivotaltracker.com/story/show/164245943)
I have…
- Creates a new `External Link` field on the `SME Document` content type
- Makes the `document_file` field optional
- edits the 
1. Pull code; import config; compile theme assets; clear cache
1. Create new SME Document node with no file upload, a link url, an SME Section value of "On-line Education Series", no updated date, and an archive date in the future. This will ensure it's easy to find...
1. Go to `/sme` and scroll to the bottom. The link should be there and work as an external link to the url you …
> links added to SME section

- web/themes/custom/move_mil/templates/layout/page--front.html.twig
- web/themes/custom/move_mil/templates/layout/page.html.twig
Additional follow-up request from Jared. See https://www.pivotaltracker.com/story/show/164551836
I have…
- Adds a line of text above TRANSCOM in the footer of both the front page and internal pages
1. Pull code
1. View the footer on the home page to see new text
1. Do the same on any interior page
> add additional text "Maintained by" to updated footer logo area

- web/modules/custom/locations/src/Form/ManagerForm.php
- web/modules/custom/locations/src/Service/Writer.php
I have…
- Uses "{$zipcode}, {$city}, {$country}" for US offices
- Uses "{$city}, {$country}" for non-US offices
- Remove the usage of office name, since is not correct for some offices.
1. Pull the changes
1. Use the uploader
1. Check offices on the locator maps tool
> Use other fields from the xml to find the geolocation of the office

- config/sync/views.view.sme_section.yml
Triages a minor residual bug on the SME page that has already been fixed on Prod. This update simply persists that configuration change.
I have…
Before (staging):
After (prod & local):
> hide all active SME Section view blocks with no content

- web/modules/custom/locations/src/Service/Reader.php
- web/modules/custom/locations/src/Service/Writer.php
I have…
- Use complete country name instead of country code to add in the geolocate API call, since some locations within the XML come without the country code.
- Limit geolocalization for transportation offices only.
1. Pull branch
1. Use locations uploader tool to upload an XML file.
1. When looking for Illinois you should not see an office from Russia.
1. When looking for Russia, you should see the "NONE" location, which is the USA consulate on Russia.
> Geolocate only Transportation offices, by complete country name

- web/modules/custom/locations/src/Form/ManagerForm.php
I have…
- Initialize locations config with an empty array
1. You shouldn't see this error "Warning: count(): Parameter must be an array or an object that implements Countable in Drupal\locations\Form\ManagerForm->buildForm() (line 132 of modules/custom/locations/src/Form/ManagerForm.php)."
> Initialize locations config with empty array

- web/modules/custom/react_tools/tools/apps/react-locator-map/src/App.js
- web/modules/custom/react_tools/tools/apps/react-locator-map/src/components/locatorMap.js
- web/modules/custom/react_tools/tools/apps/react-ppm-tool/src/App.js
- web/modules/custom/react_tools/tools/config/env.js
- web/modules/custom/react_tools/tools/package-lock.json
- web/modules/custom/react_tools/tools/package.json
In react apps, updates the `webpack-dev-server` version to allow `npm start` to run properly, moves it to devDependencies to avoid vulnerabilities in prod environment, and updates the package-lock.json accordingly. Also fixes a bug in the react app that had made it to the staging site but not yet to prod, and was preventing the weight estimator from working properly. If successful, all four apps should work properly in local Drupal (and eventually on staging & prod).
No JIRA ticket (yet?) for this one.
I have…
- See summary above
1. Pull code
1. Go to `web/modules/custom/react_tools/tools`
1. Run `npm install`
1. Run `npm start` and load EACH of the four apps locally. They should all at least load …
> Triage react app versioning and paths

- web/modules/custom/locations/src/Service/Writer.php
I have…
- Add 'UNITED STATES' to the validation to know if the city is a US city or other county city. As opposed to us 'US'.
1. BLUE GRASS ARMY DEPOT should be geolocated on Kentucky as opposed to Virginia.
> add UNITED STATES to validate is a US city

- .ebextensions/cwl-webrequest-metrics.config
- docker/Dockerfile
- docker/nginx.conf
I have…
- pulls nginx logs into cloud watch logs
1. deploy new version to AWS
2. check that the "Logs" page contains access.log entries
> set up cloud watch to gather nginx access logs

- composer.json
- composer.lock
I have…
- Downgrading drupal/console (1.9.1 => 1.8.0) because 1.9.1 has a lot of issues with translation: memory leaks, and erroring when building the image.
> Downgrading drupal/console (1.9.1 => 1.8.0)

- .env.docker.example
- docker/Dockerfile
This PR upgrades the version of PHP to 7.4. 
This pull request upgrades both the docker build image and running container images to PHP 7.4. I've so far tested by running an instance of the site locally, and checked for any errors in the logs.
> Upgrade to PHP 7.4
